# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "ubuntu/trusty64"
  config.ssh.forward_agent = true
  config.ssh.insert_key = false
  config.vm.define "vagrant1" do |vagrant1|
    vagrant1.vm.box = "ubuntu/trusty64"
    vagrant1.vm.network "private_network", ip:"10.0.0.2"
    vagrant1.vm.provider "virtualbox" do |v|
      v.name = "Ansible 101 - Task 3: Frontend1"
      v.memory = 256
    end
  end
  config.vm.define "vagrant2" do |vagrant2|
    vagrant2.vm.box = "ubuntu/trusty64"
    vagrant2.vm.network "private_network", ip:"10.0.0.3"
    vagrant2.vm.provider "virtualbox" do |v|
      v.name = "Ansible 101 - Task 3: Frontend2"
      v.memory = 256
    end
  end
  config.vm.define "vagrant3" do |vagrant3|
    vagrant3.vm.box = "ubuntu/trusty64"
    vagrant3.vm.network "private_network", ip:"10.0.0.4"
    vagrant3.vm.provider "virtualbox" do |v|
      v.name = "Ansible 101 - Task 3: Database"
      v.memory = 256
    end
  end
end
